name: ig_vae
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2021.4.13
  - certifi=2020.12.5
  - cpuonly=1.0
  - ffmpeg=4.3
  - freetype=2.10.4
  - gmp=6.2.1
  - gnutls=3.6.15
  - intel-openmp=2021.2.0
  - jpeg=9b
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.33.1
  - libffi=3.3
  - libgcc-ng=9.1.0
  - libiconv=1.15
  - libidn2=2.3.0
  - libpng=1.6.37
  - libstdcxx-ng=9.1.0
  - libtasn1=4.16.0
  - libtiff=4.1.0
  - libunistring=0.9.10
  - libuv=1.40.0
  - lz4-c=1.9.3
  - mkl=2021.2.0
  - mkl-service=2.3.0
  - mkl_fft=1.3.0
  - mkl_random=1.2.1
  - ncurses=6.2
  - nettle=3.7.2
  - ninja=1.10.2
  - numpy=1.20.1
  - numpy-base=1.20.1
  - olefile=0.46
  - openh264=2.1.0
  - openssl=1.1.1k
  - pillow=8.2.0
  - pip=21.0.1
  - python=3.7.10
  - pytorch=1.8.1
  - readline=8.1
  - setuptools=52.0.0
  - six=1.15.0
  - sqlite=3.35.4
  - tk=8.6.10
  - torchaudio=0.8.1
  - torchvision=0.9.1
  - tqdm=4.59.0
  - typing_extensions=3.7.4.3
  - wheel=0.36.2
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.4.9
